export enum CoffeeImageNames {
  'traditional-expresso' = 'Expresso',
  'american-expresso' = 'Americano',
  'creamy-expresso' = 'Expresso Cremoso',
  'cold-expresso' = 'Café Gelado',
  'coffee-milk' = 'Café com Leite',
  'latte' = 'Latte',
  'cappuccino' = 'Capuccino',
  'macchiato' = 'Macchiato',
  'mocaccino' = 'Mochaccino',
  'hot-chocolate' = 'Chocolate Quente',
  'cuban' = 'Cubano',
  'havaian' = 'Havaiano',
  'arabian' = 'Árabe',
  'irish' = 'Irlandês',
}

export type Coffee = (typeof CoffeeMenu)[0];

export const CoffeeMenu = [
  {
    id: 1,
    name: 'traditional-expresso',
    price: 9.9,
    title: 'Expresso Tradicional',
    description: 'O tradicional café feito com água quente e grãos moídos',
    badges: ['TRADICIONAL'],
    image: CoffeeImageNames['traditional-expresso'],
  },
  {
    id: 2,
    name: 'american-expresso',
    price: 9.9,
    title: 'Expresso Americano',
    description: 'Expresso diluído, menos intenso que o tradicional',
    badges: ['TRADICIONAL'],
    image: CoffeeImageNames['american-expresso'],
  },
  {
    id: 3,
    name: 'creamy-expresso',
    price: 9.9,
    title: 'Expresso Cremoso',
    description: 'Café expresso tradicional com espuma cremosa',
    badges: ['TRADICIONAL'],
    image: CoffeeImageNames['creamy-expresso'],
  },
  {
    id: 4,
    name: 'cold-expresso',
    price: 9.9,
    title: 'Expresso Gelado',
    description: 'Bebida preparada com café expresso e cubos de gelo',
    badges: ['TRADICIONAL', 'GELADO'],
    image: CoffeeImageNames['cold-expresso'],
  },
  {
    id: 5,
    name: 'coffee-milk',
    price: 9.9,
    title: 'Café com Leite',
    description: 'Meio a meio de expresso tradicional com leite vaporizado',
    badges: ['TRADICIONAL', 'COM LEITE'],
    image: CoffeeImageNames['coffee-milk'],
  },
  {
    id: 6,
    name: 'latte',
    price: 9.9,
    title: 'Latte',
    description:
      'Uma dose de café expresso com o dobro de leite e espuma cremosa',
    badges: ['TRADICIONAL', 'COM LEITE'],
    image: CoffeeImageNames['latte'],
  },
  {
    id: 7,
    name: 'cappuccino',
    price: 9.9,
    title: 'Cappuccino',
    description:
      'Bebida com canela feita de doses iguais de café, leite e espuma',
    badges: ['TRADICIONAL', 'COM LEITE'],
    image: CoffeeImageNames['cappuccino'],
  },
  {
    id: 8,
    name: 'macchiato',
    price: 9.9,
    title: 'Macchiato',
    description:
      'Café expresso misturado com um pouco de leite quente e espuma',
    badges: ['TRADICIONAL', 'COM LEITE'],
    image: CoffeeImageNames['macchiato'],
  },
  {
    id: 9,
    name: 'mocaccino',
    price: 9.9,
    title: 'Mocaccino',
    description: 'Café expresso com calda de chocolate, pouco leite e espuma',
    badges: ['TRADICIONAL', 'COM LEITE'],
    image: CoffeeImageNames['mocaccino'],
  },
  {
    id: 10,
    name: 'hot-chocolate',
    price: 9.9,
    title: 'Chocolate Quente',
    description: 'Bebida feita com chocolate dissolvido no leite quente e café',
    badges: ['ESPECIAL', 'COM LEITE'],
    image: CoffeeImageNames['hot-chocolate'],
  },
  {
    id: 11,
    name: 'cuban',
    price: 9.9,
    title: 'Cubano',
    description:
      'Drink gelado de café expresso com rum, creme de leite e hortelã',
    badges: ['ESPECIAL', 'ALCOÓLICO', 'GELADO'],
    image: CoffeeImageNames['cuban'],
  },
  {
    id: 12,
    name: 'havaian',
    price: 9.9,
    title: 'Havaiano',
    description: 'Bebida adocicada preparada com café e leite de coco',
    badges: ['ESPECIAL'],
    image: CoffeeImageNames['havaian'],
  },
  {
    id: 13,
    name: 'arabian',
    price: 9.9,
    title: 'Árabe',
    description: 'Bebida preparada com grãos de café árabe e especiarias',
    badges: ['ESPECIAL'],
    image: CoffeeImageNames['arabian'],
  },
  {
    id: 14,
    name: 'irish',
    price: 9.9,
    title: 'Irlandês',
    description: 'Bebida a base de café, uísque irlandês, açúcar e chantilly',
    badges: ['ESPECIAL', 'ALCOÓLICO'],
    image: CoffeeImageNames['irish'],
  },
];
